name: BasicPluginPack
main: com.gmail.jackdonofrio99.BasicPluginPack
version: 1.0
api-version: 1.13
author: Jack1q
commands:
   joindate:
      description: displays a player's joindate.
      permission: basicpluginpack.joindate
      usage: /joindate (username)
   sethome:
      description: sets a player's home.
      permission: basicpluginpack.sethome
      usage: /sethome
   home:
      description: teleports player home
      permission: basicpluginpack.home
      usage: /home
   wherehome:
      description: gives player home location details
      permission: basicpluginpack.wherehome
      usage: /wherehome
   mute:
      description: mutes players who are misbehaving
      permission: basicpluginpack.mute
      usage: /mute (username)
   unmute:
      description: unmutes players who have been muted
      permission: basicpluginpack.unmute
      usage: /unmute (username)
   setspawn: 
      description: sets the world spawn at current location
      permission: basicpluginpack.setspawn
      usage: /setspawn
   spawn:
      description: teleports player to spawn
      permission: basicpluginpack.spawn
      usage: /spawn
   lastseen:
      description: tells you when a player last logged in
      permission: basicpluginpack.lastseen
      usage: /lastseen (player)
   msg: 
      description: sends private message to player
      permission: basicpluginpack.msg
      usage: /msg (player) (message)
   reply:
      description: responds to last player to msg you
      permission: basicpluginpack.reply
      usage: /reply (message)

permissions:
   basicpluginpack.joindate: 
      description: Allows you to see a player's join date.
      default: true
   basicpluginpack.sethome: 
      description: Allows you to set a home warp location
      default: true
   basicpluginpack.home: 
      description: Allows you to teleport to your set home location.
      default: true
   basicpluginpack.wherehome: 
      description: Allows you to see details about set home location.
      default: true
   basicpluginpack.mute:
      description: Allows you to mute players.
      default: op
   basicpluginpack.unmute:
      description: Allows you to unmute players.
      default: op
   basicpluginpack.setspawn:
      description: Allows you to set spawn location.
      default: op
   basicpluginpack.spawn:
      description: Allows you to teleport to spawn.
      default: true
   basicpluginpack.lastseen:
      description: Allows you to see when a player last joined
      default: true
   basicpluginpack.msg:
      description: Allows you to send a message to a player
      default: true
   basicpluginpack.reply:
      description: Allows you to reply to a player
      default: true
